language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

cache: yarn

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database tasksreact;'
  - composer self-update
  - composer install --dev --prefer-source --no-interaction
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - yarn install
  - yarn run dev
  - php artisan serve
